image: alpine

clone:
  depth: full # SonarQube Cloud scanner needs the full history to assign issues properly

definitions:
  services:
    docker:
      memory: 2048
  caches:
    sonar: ~/.sonar/cache

pipelines:
  default:
    - step:
        name: Security & Quality Scan
        caches:
          - sonar
          - docker
        script:
          - pipe: sonarsource/sonarcloud-scan:4.1.0
            variables:
              SONAR_TOKEN: $SONAR_TOKEN
