[tool.coverage.run]
source = ["."]
omit = [
    "Testing/*",
    "tests/*",
    "*/__pycache__/*",
    "*/test_*",
    "venv/*",
    ".venv/*",
    "env/*",
    ".env/*"
]
branch = true
relative_files = true

[tool.coverage.report]
show_missing = true
skip_covered = false
precision = 2
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
]

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.xml]
output = "coverage.xml"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--disable-warnings",
    "--tb=short",
]
markers = [
    "integration: marks tests as integration tests (may require external resources)",
    "unit: marks tests as unit tests",
]